### ISSUE TITLE
[Feature request] Support BGRA Pixel Format

### ISSUE THREAD

**Issue by 0Ky** [oddity-ai/video-rs#24]
It would be nice to also support other pixel formats, including `AV_PIX_FMT_BGRA`. I use the `BGRA` format as the DXGI Desktop Duplication API provides screen captures in the `DXGI_FORMAT_B8G8R8A8_UNORM` (BGRA) pixel format and I believe FFmpeg can handle the pixel format conversion from `BGRA` to `YUV420p`.

**Comment by gerwin3** [comment]
Yeah, would be great. Unfortunately it is quite a bit of work since they create now assumes RGB24 everywhere to simplify conversion for ndarray. One approach could be to add an API for the user to choose how the `AvScaler` target pixel format and then have `ndarray` conversion panic if it is not RGB24, or alternatively we'd need to map all possible pixel formats to ndarray copy procedures / formats....
